// <auto-generated />
using System;
using Accounts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accounts.Migrations
{
    [DbContext(typeof(AccountsContext))]
    [Migration("20210613190159_M001")]
    partial class M001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accounts.Data.Classes.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("TimeStamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Zombie")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Accounts.Data.Classes.Organization", b =>
                {
                    b.HasBaseType("Accounts.Data.Classes.Item");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Accounts.Data.Classes.User", b =>
                {
                    b.HasBaseType("Accounts.Data.Classes.Item");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Accounts.Data.Classes.Organization", b =>
                {
                    b.HasOne("Accounts.Data.Classes.Item", null)
                        .WithOne()
                        .HasForeignKey("Accounts.Data.Classes.Organization", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts.Data.Classes.User", b =>
                {
                    b.HasOne("Accounts.Data.Classes.Item", null)
                        .WithOne()
                        .HasForeignKey("Accounts.Data.Classes.User", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Accounts.Data.Classes.Organization", null)
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("Accounts.Data.Classes.Organization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
